/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view.multa;

import bancodados.IBanco;
import bancodados.server.IServer;
import dao.DAOFactory;
import dao.MultaDAO;
import dao.ProprietarioDAO;
import dao.VeiculoDAO;
import java.util.List;
import javax.swing.table.TableModel;
import modelo.Multa;
import tablemodel.TableModelMulta;
import util.FormUtil;

/**
 *
 * @author Administrador
 */
public class CadastroMulta extends javax.swing.JFrame {

    private IBanco banco;
    private IServer server;
    private MultaDAO dao;
    private ProprietarioDAO daoProprietario;
    private VeiculoDAO daoVeiculo;
    private TableModelMulta tableModelMulta;

    public IBanco getBanco() {
        return banco;
    }

    public void setBanco(IBanco banco) {
        this.banco = banco;
    }

    /**
     * Creates new form CadastroProprietario
     */
    public CadastroMulta() {
        initComponents();
        FormUtil.centraliza(this);
        tableModelMulta = new TableModelMulta();
        tableMultas.setModel(tableModelMulta);
    }

    public void setarDAO() {
        this.dao = DAOFactory.getMultaDAO(banco);
        this.daoProprietario = DAOFactory.getProprietarioDAO(banco);
        this.daoVeiculo = DAOFactory.getVeiculoDAO(banco);
        updateTable();
    }

    public void updateTable() {
        List<Multa> multas = dao.getMultas();
        tableModelMulta.setLinhas(multas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioBuscar = new javax.swing.ButtonGroup();
        jToolBar1 = new javax.swing.JToolBar();
        buttonIncluir = new javax.swing.JButton();
        buttonExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableMultas = new javax.swing.JTable();
        radioProprietario = new javax.swing.JRadioButton();
        radioVeiculo = new javax.swing.JRadioButton();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();

        radioBuscar.add(radioProprietario);
        radioBuscar.add(radioVeiculo);

        setTitle("Multas");
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);

        jToolBar1.setRollover(true);

        buttonIncluir.setText("Incluir");
        buttonIncluir.setFocusable(false);
        buttonIncluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonIncluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonIncluirActionPerformed(evt);
            }
        });
        jToolBar1.add(buttonIncluir);

        buttonExcluir.setText("Excluir");
        buttonExcluir.setFocusable(false);
        buttonExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExcluirActionPerformed(evt);
            }
        });
        jToolBar1.add(buttonExcluir);

        tableMultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableMultas);

        radioBuscar.add(radioProprietario);
        radioProprietario.setSelected(true);
        radioProprietario.setText("Proprietario");

        radioBuscar.add(radioVeiculo);
        radioVeiculo.setText("Veiculo");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(radioProprietario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radioVeiculo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioProprietario)
                    .addComponent(radioVeiculo)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonIncluirActionPerformed
        CadastroDialogMulta cad = new CadastroDialogMulta(this, true);
        cad.setDaoProprietario(daoProprietario);
        cad.setDaoVeiculo(daoVeiculo);
        cad.setVisible(true);
        if (cad.isOk()) {
            dao.insertMulta(cad.getMulta());
            updateTable();
        }
    }//GEN-LAST:event_buttonIncluirActionPerformed

    private void buttonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExcluirActionPerformed
        int selRow = tableMultas.getSelectedRow();

        if (selRow != -1) {
            dao.deleteMulta((Integer) tableModelMulta.getValueAt(selRow, 0));
            updateTable();
        }
    }//GEN-LAST:event_buttonExcluirActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if (txtBuscar.getText().trim().isEmpty()) {
            updateTable();
        } else {
            List<Multa> multas;
            if (radioProprietario.isSelected()) {
                multas = dao.findByProprietario(txtBuscar.getText());
            } else {
                multas = dao.findByVeiculo(txtBuscar.getText());
            }
            tableModelMulta.setLinhas(multas);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroMulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroMulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroMulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroMulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroMulta().setVisible(true);
            }
        });
    }

    public TableModel getTableModelProprietario() {
        return this.tableModelMulta;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton buttonExcluir;
    private javax.swing.JButton buttonIncluir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.ButtonGroup radioBuscar;
    private javax.swing.JRadioButton radioProprietario;
    private javax.swing.JRadioButton radioVeiculo;
    private javax.swing.JTable tableMultas;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
