/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view.logradouro;

import bancodados.IBanco;
import dao.DAOFactory;
import dao.LogradouroDAO;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import modelo.Logradouro;
import tablemodel.TableModelLogradouro;
import util.FormUtil;

/**
 *
 * @author Administrador
 */
public class CadastroLogradouro extends JDialog {

    private Logradouro logradouro;
    private LogradouroDAO dao;
    private IBanco banco;
    private TableModelLogradouro tableModelLogradouro;

    public Logradouro getLogradouro() {
        return logradouro;
    }

    public CadastroLogradouro(JDialog owner, boolean modal, IBanco banco) {
        super(owner,modal);
        initComponents();
        FormUtil.centraliza(this);
        this.banco = banco;
        tableModelLogradouro = new TableModelLogradouro();
        tableLogradouro.setModel(tableModelLogradouro);
        setarDAO();
    }

    public void setarDAO() {
        this.dao = DAOFactory.getLogradouroDAO(banco);
        updateTable();
    }

    public void updateTable() {
        List<Logradouro> logs = dao.getLogradouros();
        tableModelLogradouro.setLinhas(logs);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableLogradouro = new javax.swing.JTable();
        brnCancelar = new javax.swing.JButton();
        btnOk = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        btnIncluir = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);

        tableLogradouro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tableLogradouro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableLogradouroMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableLogradouro);

        brnCancelar.setText("Cancelar");
        brnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnCancelarActionPerformed(evt);
            }
        });

        btnOk.setText("Ok");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        jToolBar1.setRollover(true);

        btnIncluir.setText("Incluir");
        btnIncluir.setFocusable(false);
        btnIncluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnIncluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });
        jToolBar1.add(btnIncluir);

        btnExcluir.setText("Excluir");
        btnExcluir.setFocusable(false);
        btnExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        jToolBar1.add(btnExcluir);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(162, Short.MAX_VALUE)
                .addComponent(btnOk)
                .addGap(18, 18, 18)
                .addComponent(brnCancelar)
                .addGap(138, 138, 138))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOk)
                    .addComponent(brnCancelar)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveLogradouroAndDispose() {
        Integer codLog = (Integer) tableModelLogradouro.getValueAt(
                tableLogradouro.getSelectedRow(), 0);

        logradouro = dao.findById(codLog);

        this.dispose();
    }

    private void tableLogradouroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableLogradouroMouseClicked
        if (evt.getClickCount() == 2) {
            if (tableLogradouro.getSelectedRow() != -1) {
                saveLogradouroAndDispose();
            }
        }
    }//GEN-LAST:event_tableLogradouroMouseClicked

    private void brnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_brnCancelarActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        if (tableLogradouro.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um logradouro");
        } else {
            saveLogradouroAndDispose();
        }
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
        IncluirLogradouroDialog dlg = new IncluirLogradouroDialog(this, true);
        dlg.setVisible(true);
        if (dlg.getLogradouro() != null) {
            Logradouro l = dlg.getLogradouro();
            dao.insertLogradouro(l);
            updateTable();
        }
    }//GEN-LAST:event_btnIncluirActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (tableLogradouro.getSelectedRow() != -1) {
            int result = JOptionPane.showConfirmDialog(this, "Deseja realmente excluir este objeto?", "Confirmação", JOptionPane.YES_NO_OPTION);
            switch (result) {
                case 0:
                    int row = tableLogradouro.getSelectedRow();
                    dao.deleteLogradouro((Integer) tableModelLogradouro.getValueAt(row, 0));
                    updateTable();
                case 1:
                    break;
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JButton btnOk;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tableLogradouro;
    // End of variables declaration//GEN-END:variables
}
